// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXD_VBH4gKujI9gzTg-gezjIcLm81mixw',
    appId: '1:414380149787:web:f9fdd11bb5c6e65dfdfcbe',
    messagingSenderId: '414380149787',
    projectId: 'biblioteca-ad192',
    authDomain: 'biblioteca-ad192.firebaseapp.com',
    storageBucket: 'biblioteca-ad192.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIoItamsmDlpIsh2TpRTdSgI90QfE5wLk',
    appId: '1:414380149787:android:f960ff67cac9b21cfdfcbe',
    messagingSenderId: '414380149787',
    projectId: 'biblioteca-ad192',
    storageBucket: 'biblioteca-ad192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuH2BA6r81dBehncLpPq5dxD7ucipcwxU',
    appId: '1:414380149787:ios:d0e44f9275f2813afdfcbe',
    messagingSenderId: '414380149787',
    projectId: 'biblioteca-ad192',
    storageBucket: 'biblioteca-ad192.appspot.com',
    iosClientId: '414380149787-scpumq7ms62niplrl6bbs1mo8sj0d28h.apps.googleusercontent.com',
    iosBundleId: 'com.leya1001.biblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuH2BA6r81dBehncLpPq5dxD7ucipcwxU',
    appId: '1:414380149787:ios:d0e44f9275f2813afdfcbe',
    messagingSenderId: '414380149787',
    projectId: 'biblioteca-ad192',
    storageBucket: 'biblioteca-ad192.appspot.com',
    iosClientId: '414380149787-scpumq7ms62niplrl6bbs1mo8sj0d28h.apps.googleusercontent.com',
    iosBundleId: 'com.leya1001.biblioteca',
  );
}
